// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsyHGm1lusJOmEMD7FYSL6cpnfj_kfv0I',
    appId: '1:133657886949:web:03c9c679f021786b8d540c',
    messagingSenderId: '133657886949',
    projectId: 'global-notebook',
    authDomain: 'global-notebook.firebaseapp.com',
    storageBucket: 'global-notebook.firebasestorage.app',
    measurementId: 'G-G7X8NTC45E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjl4hwLPuML_E_oj-PXbrFDKUREVSOSsM',
    appId: '1:133657886949:android:b3ecfbef177e34888d540c',
    messagingSenderId: '133657886949',
    projectId: 'global-notebook',
    storageBucket: 'global-notebook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZD_KpbkOq32JxFxoBB_DGfOjuZaphZLg',
    appId: '1:133657886949:ios:70b56ac3581258f08d540c',
    messagingSenderId: '133657886949',
    projectId: 'global-notebook',
    storageBucket: 'global-notebook.firebasestorage.app',
    iosBundleId: 'com.example.curationDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZD_KpbkOq32JxFxoBB_DGfOjuZaphZLg',
    appId: '1:133657886949:ios:70b56ac3581258f08d540c',
    messagingSenderId: '133657886949',
    projectId: 'global-notebook',
    storageBucket: 'global-notebook.firebasestorage.app',
    iosBundleId: 'com.example.curationDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsyHGm1lusJOmEMD7FYSL6cpnfj_kfv0I',
    appId: '1:133657886949:web:74766705b8c4b0788d540c',
    messagingSenderId: '133657886949',
    projectId: 'global-notebook',
    authDomain: 'global-notebook.firebaseapp.com',
    storageBucket: 'global-notebook.firebasestorage.app',
    measurementId: 'G-K8QY7HSWYF',
  );
}
