// Ensure the package name matches your project name in pubspec.yaml
// If you named your project 'notebook_app', it should be:
// import 'package:notebook_app/submission_page.dart';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';
import 'package:image/image.dart' as img;
import 'package:signature/signature.dart';
import 'package:image_picker/image_picker.dart';

//firebase imports
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // The file generated by flutterfire
// Fixes 'FirebaseStorage'
import 'package:cloud_firestore/cloud_firestore.dart'; // Fixes 'FirebaseFirestore' & 'FieldValue'
import 'package:flutter_dotenv/flutter_dotenv.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: "env");
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const GlobalNotebookApp());
}

class GlobalNotebookApp extends StatelessWidget {
  const GlobalNotebookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Global Notebook',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      // This calls the widget code I provided earlier
      home: const SubmissionPlatform(),
    );
  }
}

// Paste the "class SubmissionPlatform extends StatefulWidget..."
// code I gave you in the previous message right here below this line.
class SubmissionPlatform extends StatefulWidget {
  const SubmissionPlatform({super.key});

  @override
  State<SubmissionPlatform> createState() => _SubmissionPlatformState();
}

class _SubmissionPlatformState extends State<SubmissionPlatform> {
  int _currentStep = 0;
  // Form Controllers
  final TextEditingController _storyController = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _contactController = TextEditingController();
  final TextEditingController _selectedCountryController =
      TextEditingController();

  String _outputStyle = "Classic Cursive";

  // Handwriting Controller
  final SignatureController _signatureController = SignatureController(
    penStrokeWidth: 3,
    penColor: Colors.black,
    exportBackgroundColor: Colors.transparent,
  );

  // Image Upload State
  XFile? _pickedImage;

  void _nextStep() => setState(() => _currentStep++);
  void _prevStep() => setState(() => _currentStep--);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("The Global Notebook"),
        actions: [
          IconButton(
            icon: const Icon(Icons.auto_stories),
            tooltip: "View Virtual Notebook",
            onPressed: () async {
              final Uri url = Uri.parse('http://localhost:8000');
              if (!await launchUrl(url)) {
                debugPrint("Could not launch Virtual Notebook.");
              }
            },
          ),
        ],
      ),
      body: Stepper(
        type: StepperType.horizontal,
        currentStep: _currentStep,
        onStepContinue: _currentStep < 2 ? _nextStep : _submitStory,
        onStepCancel: _currentStep > 0 ? _prevStep : null,
        steps: [_buildInputStep(), _buildStyleStep(), _buildIdentityStep()],
      ),
    );
  }

  // STEP 1: CHOOSE INPUT METHOD
  Step _buildInputStep() {
    return Step(
      title: const Text("Your Story"),
      content: Column(
        children: [
          const Text("How would you like to share your story?"),
          const SizedBox(height: 20),
          DefaultTabController(
            length: 3,
            child: Column(
              children: [
                const TabBar(
                  labelColor: Colors.blue,
                  tabs: [
                    Tab(icon: Icon(Icons.keyboard), text: "Type"),
                    Tab(icon: Icon(Icons.edit_note), text: "Draw"),
                    Tab(icon: Icon(Icons.camera_alt), text: "Photo"),
                  ],
                ),
                SizedBox(
                  height: 300,
                  child: TabBarView(
                    children: [
                      // Keyboard Input
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: _storyController,
                          maxLines: 10,
                          decoration: const InputDecoration(
                            hintText: "Write here...",
                          ),
                        ),
                      ),
                      // Handwriting Input
                      Column(
                        children: [
                          Signature(
                            controller: _signatureController,
                            height: 200,
                            backgroundColor: Colors.grey[200]!,
                          ),
                          TextButton(
                            onPressed: () => _signatureController.clear(),
                            child: const Text("Clear"),
                          ),
                        ],
                      ),
                      // Photo Input
                      Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          if (_pickedImage != null)
                            Text("Image Selected: ${_pickedImage!.name}"),
                          ElevatedButton(
                            onPressed: () async {
                              final img = await ImagePicker().pickImage(
                                source: ImageSource.gallery,
                              );
                              setState(() => _pickedImage = img);
                            },
                            child: const Text("Upload Handwriting Photo"),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // STEP 2: SELECT OUTPUT STYLE
  Step _buildStyleStep() {
    return Step(
      title: const Text("Style"),
      content: Column(
        children: [
          DropdownButton<String>(
            value: _outputStyle,
            items: [
              "Classic Cursive",
              "Modern Print",
              "Architect",
              "Custom Sample",
            ].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),
            onChanged: (val) => setState(() => _outputStyle = val!),
          ),
          if (_outputStyle == "Custom Sample")
            ElevatedButton(
              onPressed: () {
                /* Trigger file picker for font template */
              },
              child: const Text("Upload Font Sample Template"),
            ),
        ],
      ),
    );
  }

  // STEP 3: IDENTITY & CONTACT
  Step _buildIdentityStep() {
    return Step(
      title: const Text("Submit"),
      content: Column(
        children: [
          TextField(
            controller: _nameController,
            decoration: const InputDecoration(labelText: "Name/Nickname"),
          ),
          TextField(
            controller: _contactController,
            decoration: const InputDecoration(labelText: "Email/Social Media"),
          ),
          TextField(
            controller: _selectedCountryController,
            decoration: const InputDecoration(labelText: "Homecountry"),
          ),
          // Add a Country Picker here
        ],
      ),
    );
  }

  Future<void> _submitStory() async {
    // Show loading indicator
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    final storyRef = FirebaseFirestore.instance.collection('stories').doc();

    try {
      List<String> base64Pages = [];
      String fullOcrText = "";

      // Collect typed text
      String typedText = _storyController.text.trim();

      // Pull the key from the .env file
      final String apiKey = dotenv.get('GOOGLE_VISION_API_KEY', fallback: '');

      if (apiKey.isEmpty) {
        print("Error: API Key is missing from .env file");
        return;
      }
      // 1. Process Image(s) if they exist
      // If you're using a List of images, loop through them.
      // If just one, we wrap it in a list to use the same logic.
      List<XFile> imagesToProcess = [];
      if (_pickedImage != null) {
        imagesToProcess.add(_pickedImage!);
      }
      // Optional: add your multi-image list here if you have one

      for (XFile file in imagesToProcess) {
        // Decode image from file
        final bytes = await file.readAsBytes();
        img.Image? original = img.decodeImage(bytes);

        if (original != null) {
          // Resize to 1024px width (preserves quality for OCR but saves space)
          img.Image resized = img.copyResize(original, width: 1024);

          // Compress to JPG (quality 60-70 is the sweet spot)
          List<int> compressedJpg = img.encodeJpg(resized, quality: 60);

          // Convert to Base64 and add to our array
          base64Pages.add(base64Encode(compressedJpg));
        }
      }
      // 2. Perform OCR on each page
      for (String base64Img in base64Pages) {
        final String url =
            "https://vision.googleapis.com/v1/images:annotate?key=$apiKey";

        final response = await http.post(
          Uri.parse(url),
          headers: {"Content-Type": "application/json"},
          body: jsonEncode({
            "requests": [
              {
                "image": {"content": base64Img},
                "features": [
                  {"type": "DOCUMENT_TEXT_DETECTION"},
                ],
              },
            ],
          }),
        );

        var data = jsonDecode(response.body);

        if (response.statusCode == 200) {
          var responses = data['responses'];

          if (responses != null && responses.isNotEmpty) {
            var firstResponse = responses[0];

            // Check for "fullTextAnnotation" first (it's the most structured)
            if (firstResponse['fullTextAnnotation'] != null) {
              String summarizedText =
                  firstResponse['fullTextAnnotation']['text'];
              fullOcrText += "$summarizedText\n";
              print("DEBUG: Captured fullTextAnnotation block.");
            }
            // Fallback: Manually collect all "textAnnotations" if the summary is missing
            else if (firstResponse['textAnnotations'] != null) {
              List annotations = firstResponse['textAnnotations'];
              // Index 0 is usually the combined text, but let's be safe:
              String combinedPageText = annotations[0]['description'] ?? "";
              fullOcrText += "$combinedPageText\n";
              debugPrint("DEBUG: Captured textAnnotations[0] fallback.");
            } else {
              debugPrint(
                "DEBUG: No text found in this specific image fragment.",
              );
            }
          }
        } else {
          debugPrint(
            "Vision API Error: ${response.statusCode} - ${data['error']?['message'] ?? response.body}",
          );
          throw Exception(
            "Vision API failed: ${data['error']?['message'] ?? 'Unknown error'}",
          );
        }
      }

      // Combine typed text and OCR text if both exist
      String finalContent = typedText;
      if (fullOcrText.isNotEmpty) {
        finalContent = typedText.isNotEmpty
            ? "$typedText\n\n--- OCR Transcription ---\n${fullOcrText.trim()}"
            : fullOcrText.trim();
      }

      debugPrint("FINAL TEXT TO BE SAVED: $fullOcrText");
      // 2. Save everything to Firestore
      await storyRef.set({
        'name': _nameController.text,
        'country': _selectedCountryController.text.isNotEmpty
            ? _selectedCountryController.text
            : 'The world',
        'contact': _contactController.text,
        'timestamp': FieldValue.serverTimestamp(),
        'type': base64Pages.isNotEmpty ? 'photo' : 'text',
        'pages': base64Pages,
        'text_content': finalContent,
        'status': 'pending',
      });

      _showSuccessMessage();

      // Clear the picked image after success to reset the UI
      setState(() {
        _pickedImage = null;
      });
    } catch (e) {
      print("Submit Error: $e");
      if (mounted) Navigator.pop(context); // Remove loading indicator
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Submission failed: $e")));
    } finally {
      if (mounted && Navigator.canPop(context))
        Navigator.pop(context); // Ensure loading is removed
    }
  }

  // Fix: Defining the missing method
  void _showSuccessMessage() {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text("Success!"),
        content: const Text(
          "Your story has been submitted to the global notebook.",
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text("OK"),
          ),
        ],
      ),
    );
  }
}
