import 'package:flutter/material.dart';
// Ensure the package name matches your project name in pubspec.yaml
// If you named your project 'notebook_app', it should be:
// import 'package:notebook_app/submission_page.dart';
import 'package:signature/signature.dart';
import 'package:image_picker/image_picker.dart';
//firebase imports
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // The file generated by flutterfire
import 'dart:io'; // Fixes 'File' error
import 'package:cloud_firestore/cloud_firestore.dart'; // Fixes 'FirebaseFirestore' & 'FieldValue'
import 'package:firebase_storage/firebase_storage.dart'; // Fixes 'FirebaseStorage'

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // This is the missing 'main' the error is complaining about!
  runApp(const GlobalNotebookApp());
}

class GlobalNotebookApp extends StatelessWidget {
  const GlobalNotebookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Global Notebook',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      // This calls the widget code I provided earlier
      home: const SubmissionPlatform(),
    );
  }
}

// Paste the "class SubmissionPlatform extends StatefulWidget..."
// code I gave you in the previous message right here below this line.
class SubmissionPlatform extends StatefulWidget {
  const SubmissionPlatform({super.key});

  @override
  State<SubmissionPlatform> createState() => _SubmissionPlatformState();
}

class _SubmissionPlatformState extends State<SubmissionPlatform> {
  int _currentStep = 0;
  // Form Controllers
  final TextEditingController _storyController = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _contactController = TextEditingController();
  final TextEditingController _selectedCountryController =
      TextEditingController();

  String _outputStyle = "Classic Cursive";

  // Handwriting Controller
  final SignatureController _signatureController = SignatureController(
    penStrokeWidth: 3,
    penColor: Colors.black,
    exportBackgroundColor: Colors.transparent,
  );

  // Image Upload State
  XFile? _pickedImage;

  void _nextStep() => setState(() => _currentStep++);
  void _prevStep() => setState(() => _currentStep--);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("The Global Notebook")),
      body: Stepper(
        type: StepperType.horizontal,
        currentStep: _currentStep,
        onStepContinue: _currentStep < 2 ? _nextStep : _submitStory,
        onStepCancel: _currentStep > 0 ? _prevStep : null,
        steps: [_buildInputStep(), _buildStyleStep(), _buildIdentityStep()],
      ),
    );
  }

  // STEP 1: CHOOSE INPUT METHOD
  Step _buildInputStep() {
    return Step(
      title: const Text("Your Story"),
      content: Column(
        children: [
          const Text("How would you like to share your story?"),
          const SizedBox(height: 20),
          DefaultTabController(
            length: 3,
            child: Column(
              children: [
                const TabBar(
                  labelColor: Colors.blue,
                  tabs: [
                    Tab(icon: Icon(Icons.keyboard), text: "Type"),
                    Tab(icon: Icon(Icons.edit_note), text: "Draw"),
                    Tab(icon: Icon(Icons.camera_alt), text: "Photo"),
                  ],
                ),
                SizedBox(
                  height: 300,
                  child: TabBarView(
                    children: [
                      // Keyboard Input
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextField(
                          controller: _storyController,
                          maxLines: 10,
                          decoration: const InputDecoration(
                            hintText: "Write here...",
                          ),
                        ),
                      ),
                      // Handwriting Input
                      Column(
                        children: [
                          Signature(
                            controller: _signatureController,
                            height: 200,
                            backgroundColor: Colors.grey[200]!,
                          ),
                          TextButton(
                            onPressed: () => _signatureController.clear(),
                            child: const Text("Clear"),
                          ),
                        ],
                      ),
                      // Photo Input
                      Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          if (_pickedImage != null)
                            Text("Image Selected: ${_pickedImage!.name}"),
                          ElevatedButton(
                            onPressed: () async {
                              final img = await ImagePicker().pickImage(
                                source: ImageSource.gallery,
                              );
                              setState(() => _pickedImage = img);
                            },
                            child: const Text("Upload Handwriting Photo"),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // STEP 2: SELECT OUTPUT STYLE
  Step _buildStyleStep() {
    return Step(
      title: const Text("Style"),
      content: Column(
        children: [
          DropdownButton<String>(
            value: _outputStyle,
            items: [
              "Classic Cursive",
              "Modern Print",
              "Architect",
              "Custom Sample",
            ].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),
            onChanged: (val) => setState(() => _outputStyle = val!),
          ),
          if (_outputStyle == "Custom Sample")
            ElevatedButton(
              onPressed: () {
                /* Trigger file picker for font template */
              },
              child: const Text("Upload Font Sample Template"),
            ),
        ],
      ),
    );
  }

  // STEP 3: IDENTITY & CONTACT
  Step _buildIdentityStep() {
    return Step(
      title: const Text("Submit"),
      content: Column(
        children: [
          TextField(
            controller: _nameController,
            decoration: const InputDecoration(labelText: "Name/Nickname"),
          ),
          TextField(
            controller: _contactController,
            decoration: const InputDecoration(labelText: "Email/Social Media"),
          ),
          TextField(
            controller: _selectedCountryController,
            decoration: const InputDecoration(labelText: "Homecountry"),
          ),
          // Add a Country Picker here
        ],
      ),
    );
  }

  // Added 'async' here to fix the "await_in_wrong_context" error
  Future<void> _submitStory() async {
    // Fix: Initializing the Firestore reference
    final storyRef = FirebaseFirestore.instance.collection('stories').doc();
    String? downloadUrl;

    try {
      // 1. Upload to Storage
      if (_pickedImage != null) {
        // 1. Create the File object from the path
        File file = File(_pickedImage!.path);

        // 2. Create a unique name for the image
        final storageRef = FirebaseStorage.instance.ref().child(
          'story_uploads/${DateTime.now().millisecondsSinceEpoch}.jpg',
        );

        try {
          // 3. IMPORTANT: Use 'putFile' and WAIT for it to complete
          TaskSnapshot uploadTask = await storageRef.putFile(file);

          // 4. ONLY get the URL after the task is successful
          downloadUrl = await uploadTask.ref.getDownloadURL();
        } catch (e) {
          print("Firebase Storage Error: $e");
          return; // Stop the function if the upload fails
        }
      }

      // 2. Save to Firestore
      await storyRef.set({
        'name': _nameController.text,
        // Fix: Default to 'Unknown' if _selectedCountry isn't defined yet
        'country': _selectedCountryController.text.isNotEmpty
            ? _selectedCountryController.text
            : 'The world',
        'contact': _contactController.text,
        'timestamp': FieldValue.serverTimestamp(),
        'type': _pickedImage != null ? 'photo' : 'text',
        'image_url': downloadUrl,
        'text_content': _storyController.text,
        'status': 'pending',
      });

      _showSuccessMessage();
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Submission failed: $e")));
    }
  }

  // Fix: Defining the missing method
  void _showSuccessMessage() {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text("Success!"),
        content: const Text(
          "Your story has been submitted to the global notebook.",
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text("OK"),
          ),
        ],
      ),
    );
  }
}
